create or replace view DATA_LAKE.ANALYTICS.VW_RENDER_UNITS(
	PROJECT,
	TASK_ID,
	STATUS,
	TASK_TYPE,
	WORK_PACKAGE,
	SUBSECTOR,
	LABELS_GENERAL,
	LABELS_GRANT_ID,
	LABELS_JOB_TYPE,
	LABELS_SUPERVISOR,
	LABELS_GRANT_AREAS,
	LABELS_DROP_ADMIN,
	LABELS_WORK_ORDER,
	LABELS_DROP_API,
	LABELS_WORK_CATEGORY,
	LABELS_ERP_PROJECT_ID,
	LABELS_FUNDING_POLYGONS,
	LABELS_BLUEPRINT_ID,
	ASSET_ID,
	UNIT_TYPE,
	RUS_CODE,
	UNIT_CODE,
	UNIT_DESCRIPTION,
	UOM,
	CONTRACTOR,
	INSTALLED_PER_TASK_NOTES,
	CREW_NAME,
	WORK_ACTIVITY,
	ACTUAL_QUANTITY,
	APPROVING_USER,
	APPROVED_DATE,
	COMPLETED_DATE,
	ORIGINAL_COMPLETED_DATE,
	CHANGE_REQUEST_APPROVAL_NUMBER,
	CONSTRUCTION_NOTES,
	TASK_NOTES,
	PLANNED_QUANTITY,
	STREET_ADDRESS,
	LABOR_CODE_CODE,
	LABOR_CODE_RUS_CODE,
	LABOR_CODE_DESCRIPTION,
	LABOR_CODE_UOM,
	LABOR_RATE
) as
SELECT
    u.project,
    u.task_id,
    u.status,
    u.task_type,
    u.work_package,
    u.subsector,
    u.labels_general,
    u.labels_grant_id,
    u.labels_job_type,
    u.labels_supervisor,
    u.labels_grant_areas,
    u.labels_drop_admin,
    u.labels_work_order,
    u.labels_drop_api,
    u.labels_work_category,
    u.labels_erp_project_id,
    u.labels_funding_polygons,
    u.labels_blueprint_id,
    u.asset_id,
    u.unit_type,
    u.rus_code,
    u.unit_code,                  -- already unified in base table
    u.unit_description,
    u.uom,
    u.contractor,
    u.installed_per_task_notes,
    u.crew_name,
    u.work_activity,
    u.actual_quantity,
    u.approving_user,
    u.approved_date,
    u.completed_date,
    u.original_completed_date,
    u.change_request_approval_number,
    u.construction_notes,
    u.task_notes,
    u.planned_quantity,
    u.street_address,

    /* Labor code enrichment */
    c.code        AS labor_code_code,
    c.rus_code    AS labor_code_rus_code,
    c.description AS labor_code_description,
    c.uom         AS labor_code_uom,
    c.rate        AS labor_rate

FROM DATA_LAKE.ANALYTICS.RENDER_UNITS u
LEFT JOIN DATA_LAKE.ANALYTICS.LABOR_CODES c
    ON UPPER(u.unit_code) = UPPER(c.unit_code);